### ISSUE TITLE
I am can't able to run app on device as well as can't able to create testflight build 

### ISSUE THREAD

**Issue by mahesh-rathod4** [sendbird/sendbird-live-sdk-ios#1]
I have implemented all sdk together means sendbird calls,chat and live sdk but eveything working fine on simulator but when i try to create build or try to run app on real device i got following errors  

Showing All Messages
duplicate output file '/Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/Build/Products/Debug-iphoneos/B5875743-4713-3888-BC75-F65BD7FBDE04.bcsymbolmap' on task: ProcessXCFramework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/SourcePackages/checkouts/sendbird-uikit-ios/Framework/SendbirdUIKit.xcframework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/Build/Products/Debug-iphoneos/SendbirdUIKit.framework ios

Showing All Messages
Multiple commands produce '/Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/Build/Products/Debug-iphoneos/B5875743-4713-3888-BC75-F65BD7FBDE04.bcsymbolmap'

Showing All Messages
Command: ProcessXCFramework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/SourcePackages/artifacts/sendbird-live-uikit-ios/SendbirdLiveUIKit.xcframework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/Build/Products/Debug-iphoneos/SendbirdLiveUIKit.framework ios

Showing All Messages
Command: ProcessXCFramework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/SourcePackages/checkouts/sendbird-uikit-ios/Framework/SendbirdUIKit.xcframework /Users/mtpc-283/Library/Developer/Xcode/DerivedData/App221-csehqilzqdeclublvwvqofztvexa/Build/Products/Debug-iphoneos/SendbirdUIKit.framework ios

![Screenshot 2022-11-08 at 12 37 32 PM](https://user-images.githubusercontent.com/100420105/200497599-701f41d8-ea6a-4030-94d0-926e4bb4bc56.png)

**Comment by mininny** [comment]
Hi @mahesh-rathod4 , Sorry for the trouble. It seems like there was a problem when we were packaging the sdk. We are looking into it and will release a fix soon. 

In the meantime, could you try with the `v1.0.0-beta` version of the LiveUIKit and `v1.0.0-beta.3` version of LiveSDK for now?

**Comment by mahesh-rathod4** [comment]
@mininny I have already tried https://github.com/sendbird/sendbird-live-sdk-ios/releases/tag/v1.0.0-beta.4 
but still got same error.

**Comment by mininny** [comment]
@mahesh-rathod4 The link you sent is the latest framework version. I mean can you test it with the second to the latest version of the sdks?

**Comment by mahesh-rathod4** [comment]
@mininny means v1.0.0-beta.3?

**Comment by mininny** [comment]
Yes, v1.0.0-beta.3 of the SDK and v1.0.0-beta of the UIKit https://github.com/sendbird/sendbird-live-uikit-ios/releases/tag/v1.0.0-beta.

**Comment by mahesh-rathod4** [comment]
@mininny Thank you for your help.Now working fine for me 

I have used the following sdk versions 
SenbirdLiveSDK  -> 1.0.0-beta.4
SendbirdLiveUIKit -> 1.0.0-beta

**Comment by mahesh-rathod4** [comment]
@mininny Now app successfully build but when i try run on app. my app crash after splash screen. i got following logs.

dyld[2025]: Symbol not found: (_$s13SendbirdUIKit19SBUChannelCellThemeCMn)
  Referenced from: '/private/var/containers/Bundle/Application/DBDA5322-8E73-48E7-99B4-7210D45F5764/App221.app/Frameworks/SendbirdLiveUIKit.framework/SendbirdLiveUIKit'
  Expected in: '/private/var/containers/Bundle/Application/DBDA5322-8E73-48E7-99B4-7210D45F5764/App221.app/Frameworks/SendbirdUIKit.framework/SendbirdUIKit'
Symbol not found: (_$s13SendbirdUIKit19SBUChannelCellThemeCMn)
  Referenced from: '/private/var/containers/Bundle/Application/DBDA5322-8E73-48E7-99B4-7210D45F5764/App221.app/Frameworks/SendbirdLiveUIKit.framework/SendbirdLiveUIKit'
  Expected in: '/private/var/containers/Bundle/Application/DBDA5322-8E73-48E7-99B4-7210D45F5764/App221.app/Frameworks/SendbirdUIKit.framework/SendbirdUIKit'
